(function(a){a(function(){var e=a(window),c=a("#topNav2"),f=function(){1<e.scrollTop()?c.addClass("sticky"):c.removeClass("sticky")};f();e.on("scroll",function(){f()});var b,d;a("#map").length&&(d={lat:23.790546,lng:90.375583},b=new google.maps.Map(document.getElementById("map"),{center:d,zoom:16,scrollwheel:!1,disableDefaultUI:!0,zoomControl:!0}),new google.maps.Marker({position:d,map:b,animation:google.maps.Animation.DROP,draggable:!0}));b=a("#footerTwitter");b.length&&twttr.widgets.createTimeline({sourceType:"profile",
screenName:b.data("user-name")},document.getElementById("footerTwitter"));a("#contactFrom").length&&a("#contactFrom").validate({rules:{contactName:"required",contactEmail:{required:!0,email:!0},contactMessage:"required"},errorPlacement:function(a,b){return!0},submitHandler:function(){a(".contact-form-status").show().html('<div class="alert alert-success"  role="alert">Thanks! Your message has been sent.</div>').delay(1E3).fadeOut("slow")}});a("#subscribeFormFooter").length&&a("#subscribeFormFooter").validate({rules:{EMAIL:{required:!0,
email:!0}},errorPlacement:function(a,b){return!0}});a("#subscribeForm").length&&a("#subscribeForm").validate({rules:{EMAIL:{required:!0,email:!0}},errorPlacement:function(a,b){return!0}});b=a("#postCommentForm");b.length&&b.validate({rules:{commenterName:"required",commenterComments:"required",commenterEmail:{required:!0,email:!0}},errorPlacement:function(a,b){return!0}});b=a("#loginForm");d=a("#signupForm");b.length&&b.validate({rules:{loginUsername:"required",loginPassword:"required"},errorPlacement:function(a,
b){return!0}});d.length&&d.validate({rules:{singupName:"required",singupUsername:"required",singupEmail:{required:!0,email:!0},singupPassword:"required",singupPasswordAgain:{equalTo:"#singupPassword"}},errorPlacement:function(a,b){return!0}});b=a(".header-items");d=a(".team-items");var g=a(".about-page-team-items"),h=a(".project-item-slider"),k=a(".testimonial-slider"),m=function(){a.each(this.owl.userItems,function(b){var c=jQuery(this).data("recommender-thumb"),d=jQuery(".testimonial-slider .owl-page span");
a(d[b]).html('<img src="'+c+'" alt="" class="img-responsive img-circle" />')})},l=a(".brands-slider");b.length&&b.owlCarousel({itemsSelector:".header-item",slideSpeed:1200,singleItem:!0,autoPlay:!0,addClassActive:!0});d.length&&d.owlCarousel({itemsSelector:".team-item",slideSpeed:1200,items:4,itemsTablet:[768,3],itemsTabletSmall:[480,2],itemsMobile:[320,1],autoPlay:!0});g.length&&g.owlCarousel({itemsSelector:".team-item",slideSpeed:1200,items:2,autoPlay:!0,navigation:!1});h.length&&h.owlCarousel({itemsSelector:"img",
slideSpeed:1200,singleItem:!0,autoPlay:!0});k.length&&k.owlCarousel({slideSpeed:1200,singleItem:!0,autoPlay:!0,addClassActive:!0,afterInit:m});l.length&&l.owlCarousel({slideSpeed:1200,items:4,autoPlay:!0,addClassActive:!0,pagination:!1});a("[data-img-src]").each(function(){var b=a(this).data("img-src");a(this).css("background-image","url("+b+")")});a(".facts-number").length&&a(".facts-number").counterUp({delay:10,time:1E3});a("#bgVideo").length&&a("#bgVideo .play-button").magnificPopup({delegate:"a",
type:"iframe",mainClass:"my-mfp-zoom-in"});a(".portfolio-items").length&&a(".portfolio-img-link").magnificPopup({type:"image",gallery:{enabled:!0},mainClass:"my-mfp-zoom-in"});b=a("#popupNavButton");b.length&&b.appendTo(popupNav);a(".mainNavButton").on("click",function(){a(".mainNav .mdl-layout__drawer, .mainNav .mdl-layout__obfuscator, .mdl-layout__container").toggleClass("is-visible")});a(".mainNav").on("click",".mdl-layout__obfuscator, .form-button",function(){a(".mainNav .mdl-layout__drawer, .mainNav .mdl-layout__obfuscator, .mdl-layout__container").removeClass("is-visible")});
a(".mainNav .nav > li > a").one("click",function(){a(this).parent("li").hasClass("opened")?a(this).parent("li").toggleClass("opened open"):a(this).parent("li").siblings("li.opened").toggleClass("opened open")});a(".animateScroll2 li a").on("click",function(b){b.preventDefault();b=a(this).attr("href");a(b).animatescroll({padding:-1,easing:"easeInOutExpo",scrollSpeed:1E3})});a(".animateScroll li a").on("click",function(b){b.preventDefault();b=a(this).attr("href");a(b).animatescroll({padding:58,easing:"easeInOutExpo",
scrollSpeed:1E3})});b=a(".slider-3-video");b.length&&(b.tubular({videoId:b.data("video-id"),mute:!0}),a("#tubular-player").css("height",e.outerHeight()),a("#tubular-container, #tubular-shield").appendTo(b));a(".dh-container").length&&a(".dh-container").directionalHover()});a(window).on("load",function(){a(window);if(a("#portfolio").length){var e=a(".portfolio-items");e.isotope({animationEngine:"best-available",itemSelector:".portfolio-item"});a(".portfolio-filter-menu ul").on("click",function(c){if(a(c.target).is("li")){var f=
a(c.target).data("filter");e.isotope({filter:"*"!==f?"."+f:f});a(c.target).siblings().removeClass("active");a(c.target).addClass("active")}});a(".load-more-btn").one("click",function(c){c.preventDefault();c=a(".hidden-items").html();a(".portfolio-items").append(c).isotope("reloadItems").isotope({sortBy:"original-order"});a(this).addClass("disabled");a(".dh-container").length&&a(".dh-container").directionalHover()}).on("click",function(a){a.preventDefault()})}a("#preloader .circle").fadeOut(1E3);setTimeout(function(){a("#preloader .left-door, #preloader .right-door").animate({width:["toggle",
"swing"]},1E3)},1E3)})})(jQuery);